State machine base
CESARBR/knot-android-sdk pull request #17
Opened 2020-02-11 14:16 UTC by lcc

Add base classes and the KNoT state machine manager.

2020-02-11 16:54 UTC, alla3 requested changes

2020-02-11 16:54 UTC, alla3 commented on knot-thing/src/main/java/com/cesar/knot_sdk/knot_state_machine/states/base_classes/State.kt
> +    var error : String = NO_ERROR_MESSAGE
Use a pattern for the values of the constants. Write the strings on lowercase, uppercase or the first letter in uppercase, maybe you can keep the pattern used on the next commit. Also, I think you can use the `'const'` keyword on these values.

2020-02-11 16:54 UTC, alla3 commented on knot-thing/src/main/java/com/cesar/knot_sdk/knot_state_machine/states/base_classes/State.kt
> +    val SUCCESS_MESSAGE : String = "Success"
Maybe you can change the keyword success for "Proceed" or something more appropriate.

2020-02-11 16:54 UTC, alla3 commented on knot-thing/src/main/java/com/cesar/knot_sdk/knot_state_machine/states/base_classes/State.kt
> +    abstract fun getNextState(message : String = "") : State
If you are using the default value for the message I would use the SUCCESS_MESSAGE instead of an empty string.

2020-02-11 16:54 UTC, alla3 commented on knot-thing/src/main/java/com/cesar/knot_sdk/knot_state_machine/states/base_classes/branching_state/BranchingState.kt
> +    abstract fun getAppropriateAction() : BranchingStateActions
This method's name and description are not clear enough. Please, rewrite the method's name and/or description.

2020-02-11 16:54 UTC, alla3 commented on knot-thing/src/main/java/com/cesar/knot_sdk/knot_state_machine/KNoTStateMachine.kt
> +    val PASSWORD = ""
Please, add a note specifying the developer should rewrite these constants for hardcode values. Also, I think you can use the `'const'` keyword on these values.

2020-02-11 16:54 UTC, alla3 commented on knot-thing/src/main/java/com/cesar/knot_sdk/knot_state_machine/KNoTStateMachine.kt
> +    fun operationResult(message : String = "Success") {
Maybe you can use a constant for this value.

2020-02-11 20:46 UTC, alla3 approved these changes

2020-02-20 17:37 UTC, lcc commented
This PR is outdated, a better version was submitted in #21

2020-02-20 17:37 UTC, closed without merging