Add states
CESARBR/knot-android-sdk pull request #18
Opened 2020-02-11 14:29 UTC by lcc

Add some states that compose the knot-state-machine.

Depends on #17 .

2020-02-11 16:54 UTC, alla3 requested changes
Change the commit messages in the commits you are using `from the KNoT cloud` for `from the cloud`. Since the operations should be performed by any supported cloud.

2020-02-11 19:19 UTC, alla3 approved these changes

2020-02-11 20:52 UTC, alla3 approved these changes

2020-02-20 17:38 UTC, lcc commented
This PR is outdated, a better version was sent in #22

2020-02-20 17:38 UTC, closed without merging