Add all states
CESARBR/knot-android-sdk pull request #22
Opened 2020-02-14 21:22 UTC by lcc

Add all states that compose the knot-state-machine.

Depends on #21  .

2020-02-18 22:47 UTC, alla3 requested changes

2020-02-18 22:47 UTC, alla3 commented on knot-thing/src/main/java/com/cesar/knot_sdk/knot_state_machine/states/base_classes/State.kt
> +
Remove a blank line.

2020-02-18 22:47 UTC, alla3 commented on knot-thing/src/main/java/com/cesar/knot_sdk/knot_state_machine/states/base_classes/State.kt
> +    }
The class state should not have this information.

2020-02-18 22:47 UTC, alla3 commented on knot-thing/src/main/java/com/cesar/knot_sdk/knot_state_machine/KNoTStateMachine.kt
> +
Remove a blank line.

2020-02-18 22:47 UTC, alla3 commented on knot-thing/src/main/java/com/cesar/knot_sdk/knot_state_machine/states/Unregister.kt
> +        is Ready           -> this
Should the Unregister State act as a final state? IMO It should have a transition for the Disconnect State.

2020-02-18 22:47 UTC, alla3 commented on knot-thing/src/main/java/com/cesar/knot_sdk/knot_state_machine/states/Disconnected.kt
> +
Remove this blank line.

2020-02-18 22:47 UTC, alla3 commented on knot-thing/src/main/java/com/cesar/knot_sdk/knot_state_machine/states/Registering.kt
> +        is RegNotOk        -> this
IMO it should go to Error State if the event is RegNotOk.

2020-02-19 21:12 UTC, lcc commented on knot-thing/src/main/java/com/cesar/knot_sdk/knot_state_machine/states/Unregister.kt
> +        is Ready           -> this
That could be a future improvement.

2020-02-19 21:12 UTC, lcc commented on knot-thing/src/main/java/com/cesar/knot_sdk/knot_state_machine/states/Registering.kt
> +        is RegNotOk        -> this
I agree, but I think this should be further discussed, for now, I am going to make this change.

2020-02-19 21:40 UTC, alla3 requested changes

2020-02-19 21:40 UTC, alla3 commented on knot-thing/src/main/java/com/cesar/knot_sdk/knot_state_machine/states/Online.kt
> +
Remove two blank lines.

2020-02-19 21:40 UTC, alla3 commented on knot-thing/src/main/java/com/cesar/knot_sdk/knot_state_machine/states/Registering.kt
> +        is RegNotOk        -> this
Will you change it?

2020-02-19 21:57 UTC, alla3 commented on knot-thing/src/main/java/com/cesar/knot_sdk/knot_state_machine/states/Registering.kt
> +        is RegNotOk        -> this
If you change it, make sure to update it on #23.

2020-02-20 14:14 UTC, lcc commented on knot-thing/src/main/java/com/cesar/knot_sdk/knot_state_machine/states/Online.kt
> +
Done.

2020-02-20 14:20 UTC, lcc commented on knot-thing/src/main/java/com/cesar/knot_sdk/knot_state_machine/states/Registering.kt
> +        is RegNotOk        -> this
For now, we only now that the register fails when the credentials are invalid (i.e.: someone owns the id ).Give this, I opted for generating a new ID and sending it again. We should probably look into other scenarios where register fails though.

2020-02-20 16:09 UTC, alla3 approved these changes

2020-02-20 16:10 UTC, alla3 requested changes
Solve the conflicting files.

2020-02-20 16:30 UTC, alla3 approved these changes

2020-02-20 17:07 UTC, merged